### ISSUE TITLE
Implement other metrics in verify_resources_consumption

### ISSUE THREAD

**Issue by rurod** [Secsec/openshift_upgrade_checks#6]
- [x] Add checks on memory usage
- [x] Add checks on disk usage
- [x] Add checks on requests and limits per nodes

**Comment by Secsec** [comment]
(sum(instance:node_cpu_utilisation:rate1m{job="node-exporter", instance="NODE", cluster=""} != 0) / (sum(kube_pod_resource_request{node='NODE', resource='cpu'})) )*100 
#Percentage of what is consumed regarding the overallrequests

(sum(kube_pod_resource_request{node='NODE', resource='cpu'})) / sum(node_cpu_info{instance="NODE"}) *100 
#Percentage of what requests are taking comparing to the available CPU on a given node

It can be nice to have the first one as an overview of what is really consumed, so further investigations can be done in order to tidy up some requests on a given cluster.

**Comment by Secsec** [comment]
Done for CPU, WIP on memory
